import Foundation

/// A pool of common English words for drill generation.
///
/// Deliberately real words, not keybr-style pseudo-random letter soup — the whole premise of
/// Fumble is that you should practise the things you actually type. The generator weights this
/// pool toward your weak keys and transitions (see `DrillGenerator`), so a drill is real words,
/// skewed toward the ones that exercise your specific weaknesses.
///
/// Kept lowercase and apostrophe-free-ish; a few contractions are included because they carry
/// awkward transitions worth drilling.
public enum WordList {
    public static let common: [String] = [
        "the", "and", "for", "you", "that", "with", "this", "have", "from", "they",
        "will", "would", "there", "their", "what", "about", "which", "when", "make",
        "like", "time", "just", "know", "take", "into", "year", "your", "good", "some",
        "them", "other", "than", "then", "look", "only", "come", "over", "think", "also",
        "back", "after", "work", "first", "well", "even", "want", "because", "these",
        "give", "most", "very", "through", "where", "much", "before", "right", "should",
        "people", "little", "world", "still", "between", "under", "while", "might",
        "never", "again", "another", "around", "however", "against", "during", "without",
        "place", "great", "small", "large", "different", "following", "public", "point",
        "system", "program", "question", "government", "company", "number", "group",
        "problem", "important", "several", "example", "himself", "against", "nothing",
        "something", "everything", "together", "although", "already", "always", "become",
        "change", "control", "develop", "family", "figure", "friend", "happen", "letter",
        "listen", "matter", "member", "moment", "money", "month", "morning", "mother",
        "nature", "office", "order", "other", "paper", "parent", "person", "picture",
        "power", "problem", "reason", "result", "school", "second", "series", "service",
        "simple", "single", "social", "special", "student", "study", "subject", "summer",
        "table", "teacher", "themselves", "thought", "though", "toward", "trouble",
        "understand", "water", "whether", "window", "within", "writer", "yellow",
        "quick", "brown", "jumps", "lazy", "zebra", "quartz", "phoenix", "rhythm",
        "syntax", "vector", "matrix", "buffer", "kernel", "thread", "socket", "server",
        "client", "object", "method", "return", "import", "export", "struct", "public",
        "static", "value", "index", "array", "string", "double", "boolean", "switch",
        "extend", "filter", "reduce", "append", "prefix", "suffix", "encode", "decode",
        "commit", "branch", "merge", "rebase", "config", "deploy", "verify", "assert",
        "wizard", "oxygen", "jacket", "vivid", "amazing", "buzzing", "fabric", "galaxy",
        "hazard", "injury", "jockey", "kayak", "liquid", "mimic", "nozzle", "puzzle",
        "query", "quirk", "vortex", "wobble", "yacht", "zephyr", "acknowledge", "beyond",
    ]

    /// A larger common-English pool for the adaptive trainer's natural-words blending
    /// (see `TrainerLessonGenerator`). Strictly lowercase a–z — no apostrophes or accents —
    /// because the trainer filters it against the unlocked-letter set character by character,
    /// and a stray apostrophe would silently exclude a word forever. Deliberately includes a
    /// healthy spread of q/z/x/j words so the rare-letter lessons still find real words
    /// instead of degenerating into pseudo-word soup.
    public static let english: [String] = [
        // Core function and everyday words.
        "the", "and", "for", "you", "that", "with", "this", "have", "from", "they", "will",
        "would", "there", "their", "what", "about", "which", "when", "make", "like", "time",
        "just", "know", "take", "into", "year", "your", "good", "some", "them", "other", "than",
        "then", "look", "only", "come", "over", "think", "also", "back", "after", "work", "first",
        "well", "even", "want", "because", "these", "give", "most", "very", "through", "where",
        "much", "before", "right", "should", "people", "little", "world", "still", "between",
        "under", "while", "might", "never", "again", "another", "around", "however", "against",
        "during", "without", "each", "many", "such", "those", "both", "being", "same", "here",
        "must", "every", "since", "upon", "once", "least", "along", "among", "though", "until",
        "whether", "away", "down", "does", "did", "his", "her", "him", "she", "who", "how", "why",
        "any", "may", "can", "get", "has", "had", "was", "were", "are", "not", "but", "all",
        "out", "one", "two", "six", "ten", "new", "now", "way", "day", "man", "see", "use", "its",
        "our", "own", "say", "too", "old", "off", "end",
        // Common verbs.
        "accept", "act", "add", "admit", "agree", "allow", "answer", "appear", "apply", "argue",
        "arrive", "ask", "assume", "avoid", "beat", "become", "begin", "believe", "break",
        "bring", "build", "buy", "call", "carry", "catch", "cause", "change", "check", "choose",
        "claim", "close", "compare", "consider", "contain", "continue", "cost", "cover", "create",
        "cut", "deal", "decide", "describe", "design", "determine", "develop", "die", "discover",
        "discuss", "draw", "dream", "drive", "drop", "eat", "enjoy", "enter", "exist", "expect",
        "explain", "face", "fail", "fall", "fear", "feel", "fight", "fill", "find", "finish",
        "fly", "follow", "forget", "gain", "grow", "guess", "handle", "hang", "happen", "hear",
        "help", "hide", "hit", "hold", "hope", "hurt", "identify", "imagine", "improve",
        "include", "increase", "indicate", "involve", "join", "jump", "keep", "kill", "laugh",
        "lay", "lead", "learn", "leave", "lend", "let", "lie", "listen", "live", "lose", "love",
        "maintain", "manage", "mean", "measure", "meet", "mention", "miss", "move", "need",
        "notice", "obtain", "occur", "offer", "open", "pass", "pay", "perform", "pick", "plan",
        "play", "prepare", "prevent", "produce", "protect", "prove", "provide", "pull", "push",
        "put", "raise", "reach", "read", "realize", "receive", "recognize", "record", "reduce",
        "reflect", "remain", "remember", "remove", "repeat", "report", "represent", "require",
        "rest", "return", "reveal", "rise", "run", "save", "seek", "seem", "sell", "send",
        "serve", "set", "shake", "share", "shoot", "show", "shut", "sing", "sit", "sleep",
        "speak", "spend", "stand", "start", "stay", "stop", "study", "suffer", "suggest",
        "support", "talk", "teach", "tell", "tend", "test", "thank", "throw", "touch", "train",
        "travel", "treat", "try", "turn", "visit", "wait", "walk", "watch", "wear", "win", "wish",
        "wonder", "write",
        // Common nouns.
        "action", "activity", "address", "adult", "amount", "analysis", "animal", "area",
        "authority", "baby", "bag", "ball", "bill", "bird", "blood", "board", "brain", "bread",
        "breath", "bridge", "car", "card", "care", "career", "chance", "chapter", "character",
        "charge", "citizen", "city", "class", "clock", "committee", "community", "company",
        "computer", "corner", "country", "county", "couple", "cup", "current", "customer",
        "cycle", "decade", "decision", "defense", "degree", "direction", "director", "disease",
        "distance", "drink", "driver", "drug", "earth", "election", "employee", "energy",
        "engine", "exchange", "exercise", "experience", "expert", "father", "fault", "feature",
        "feeling", "fish", "flight", "floor", "flower", "frame", "freedom", "friend", "front",
        "garden", "gas", "gift", "girl", "growth", "guard", "guest", "guide", "harm", "hat",
        "head", "health", "home", "honor", "horse", "hospital", "idea", "image", "impact",
        "income", "internet", "interview", "investment", "iron", "jelly", "jet", "job", "joke",
        "jury", "justice", "kid", "king", "lady", "lake", "land", "language", "leg", "length",
        "lesson", "letter", "lip", "list", "loan", "location", "mail", "male", "manager",
        "manner", "meal", "meaning", "media", "medicine", "milk", "mind", "minute", "mirror",
        "morning", "mother", "motion", "mountain", "nature", "neck", "network", "news", "novel",
        "number", "nurse", "object", "order", "outcome", "oven", "owner", "paper", "parent",
        "park", "part", "period", "person", "phase", "phone", "plane", "planet", "plant",
        "plastic", "poet", "point", "police", "policy", "power", "practice", "president",
        "pressure", "professor", "profile", "profit", "progress", "question", "radio", "rain",
        "range", "region", "relation", "release", "religion", "risk", "river", "road", "rock",
        "salad", "salary", "sale", "salt", "screen", "script", "sea", "season", "session",
        "shadow", "shape", "sheet", "shoulder", "side", "sign", "signal", "skin", "sky", "smile",
        "smoke", "sort", "sound", "soup", "source", "spring", "square", "stage", "stair", "stick",
        "stock", "stomach", "stone", "strength", "stress", "structure", "style", "taste", "tax",
        "tea", "teacher", "theory", "thing", "thought", "throat", "topic", "total", "tour",
        "tower", "trick", "trip", "trouble", "truck", "variety", "vehicle", "version", "video",
        "war", "warning", "waste", "water", "west", "wheel", "wife", "wind", "word", "worker",
        "worth", "writer",
        // Common adjectives and adverbs.
        "able", "actual", "afraid", "alive", "alone", "annual", "available", "aware", "basic",
        "beautiful", "big", "black", "blue", "brave", "brief", "broad", "brown", "busy", "calm",
        "capable", "central", "certain", "cheap", "clean", "clear", "cold", "common", "complete",
        "correct", "crazy", "cultural", "curious", "daily", "dark", "dead", "different",
        "difficult", "direct", "dirty", "double", "eager", "early", "easy", "economic",
        "effective", "either", "empty", "entire", "equal", "exact", "extra", "fair", "false",
        "familiar", "famous", "fast", "fat", "few", "final", "fine", "foreign", "formal",
        "former", "free", "fresh", "funny", "general", "gentle", "giant", "glad", "grand", "gray",
        "great", "green", "happy", "healthy", "heavy", "high", "honest", "hot", "hungry", "ideal",
        "important", "inner", "kind", "late", "lazy", "legal", "likely", "local", "loose", "loud",
        "low", "lucky", "main", "mental", "minor", "modern", "moral", "narrow", "natural",
        "nearby", "neat", "necessary", "negative", "nice", "normal", "obvious", "odd", "official",
        "orange", "ordinary", "original", "outer", "pale", "perfect", "personal", "physical",
        "pink", "plain", "poor", "popular", "positive", "possible", "powerful", "pretty",
        "primary", "prime", "private", "proper", "public", "pure", "purple", "quick", "quickly",
        "quite", "rapid", "rare", "raw", "ready", "recent", "red", "regular", "rich", "rough",
        "royal", "rural", "sad", "safe", "senior", "seven", "severe", "sharp", "short", "sick",
        "silly", "similar", "simple", "single", "slight", "small", "smart", "smooth", "social",
        "soft", "sorry", "special", "specific", "steady", "steep", "strange", "strict", "strong",
        "sudden", "sure", "tall", "thick", "thin", "third", "tiny", "tough", "true", "typical",
        "ugly", "unique", "useful", "usual", "vast", "warm", "weak", "white", "whole", "wide",
        "wild", "wise", "yellow", "young",
        // Rare-letter coverage: q words.
        "quest", "quit", "quote", "quiz", "quilt", "quart", "quench", "quaint", "squad",
        "squeeze", "squirrel", "request", "liquid", "frequent", "sequence", "conquer", "banquet",
        "antique", "equation", "equator", "inquiry", "acquire", "adequate", "eloquent",
        "frequency", "headquarters", "mosquito", "opaque", "technique",
        // Rare-letter coverage: z words.
        "zero", "zone", "zoo", "zoom", "zebra", "zinc", "zigzag", "zipper", "prize", "dizzy",
        "fuzzy", "pizza", "blaze", "breeze", "bronze", "frozen", "gaze", "hazard", "horizon",
        "maze", "organize", "seize", "sneeze", "wizard", "freeze", "puzzle", "amazing", "razor",
        "buzz", "graze", "hazel", "ozone", "plaza", "quartz", "zest",
        // Rare-letter coverage: x words.
        "mix", "fix", "fox", "wax", "axis", "exam", "exit", "express", "explore", "extend",
        "extreme", "sixty", "taxi", "toxic", "oxygen", "relax", "reflex", "prefix", "suffix",
        "galaxy", "luxury", "index", "complex", "expand", "expense", "example", "excuse",
        "exhibit", "expose", "maximum", "oxide", "pixel", "proxy", "sixth", "textile", "toolbox",
        "vortex", "boxer", "excess", "excite",
        // Rare-letter coverage: j words.
        "jam", "jar", "jail", "jog", "jolly", "jewel", "jealous", "jersey", "jingle", "jockey",
        "judgment", "juggle", "jumbo", "junction", "junk", "adjust", "adjacent", "inject",
        "injury", "injure", "majority", "majestic", "objective", "reject", "rejoice", "subject",
        "banjo", "enjoyment", "jasmine",
    ]
}
